POST http://localhost:3001/api/users/ 
Content-Type: application/json

{
        "userId": 1,
        "title": "prueba",
        "body": "prueba de nueva nota"
}

###

POST http://localhost:3001/api/users/ 
Content-Type: application/json

{
}